name: Run tests daily
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test
